Added the ability to use non uniform distribution for variations
rkz/flask-google-optimize pull request #9
Opened 2018-12-12 15:30 UTC by Guillaume-Caillet

Also small fix for method 'get_exp' with the 'id' parameter.

2018-12-12 18:33 UTC, rkz requested changes

2018-12-12 18:33 UTC, rkz commented on flask_google_optimize.py
> +            return [e for e in self._experiments if e.id == id][0]
Nice catch :)

2018-12-12 18:33 UTC, rkz commented on flask_google_optimize.py
> +        """
Superbe doc, j'adore !

2018-12-12 18:33 UTC, rkz commented on flask_google_optimize.py
> +        self.variations = variations  # [{'key': 'small', 'weight': 0.5},...]
Manque une validation du format et de la somme des poids = 1.

2018-12-13 08:39 UTC, Guillaume-Caillet commented on flask_google_optimize.py
> +        self.variations = variations  # [{'key': 'small', 'weight': 0.5},...]
I can add a check on the type of weight and ensuring the total is less than 1.

But having a total strictly equals to 1 is not required for the algorithm, so I'm not sure about this one. Having 2 variations both with a weight of 0.2 and 0.2 will produce the expected results : both variation will get the same probability to be chosen.

2018-12-14 08:34 UTC, merged